-- TABLE CREATION;
DROP TABLE IF EXISTS WEIGHING;
CREATE TABLE IF NOT EXISTS WEIGHING (
	SLNO	INTEGER NOT NULL,
	DCNO	VARCHAR ( 20 ),
	DCNODATE	DATE,
	CUSTOMERNAME	VARCHAR ( 100 ),
	DRIVERNAME VARCHAR ( 100 ),
	VEHICLENO	VARCHAR ( 100 ),
	MATERIAL	VARCHAR ( 100 ),
	NOOFBAGS	INTEGER,
	CHARGES	INTEGER,
	GROSSWT	INTEGER,
	GROSSDATE	DATE,
	GROSSTIME	TIME,
	TAREWT INTEGER,
	TAREDATE	DATE,
	TARETIME	TIME,
	BAGDEDUCTION	INTEGER,
	NETWT	INTEGER,
	NETDATE	DATE,
	NETTIME	TIME,
	REMARKS	VARCHAR ( 100 ),
	MANUAL BOOLEAN,
	PRIMARY KEY ( SLNO )
);
DROP TABLE IF EXISTS VEHICLETARES;
CREATE TABLE IF NOT EXISTS VEHICLETARES (
	KEY	INTEGER NOT NULL,
	CUSTOMERNAME	VARCHAR ( 100 ),
	VEHICLENO	VARCHAR ( 100 ),
	TAREWT INTEGER,
	TAREDATE	DATE,
	TARETIME	TIME,
	PRIMARY KEY ( KEY )
);
DROP TABLE IF EXISTS TRANSPORTER;
CREATE TABLE IF NOT EXISTS TRANSPORTER (
	TRANSPORTER	VARCHAR ( 100 ) NOT NULL,
	PRIMARY KEY(TRANSPORTER)
);
DROP TABLE IF EXISTS SETUP;
CREATE TABLE IF NOT EXISTS SETUP (
	ID VARCHAR ( 1 ) NOT NULL,
	UID	VARCHAR ( 100 ),
	ENDDATE	DATETIME,
	LASTLOGIN	DATETIME,
	PRIMARY KEY ( ID )
);
DROP TABLE IF EXISTS SETTINGS;
CREATE TABLE IF NOT EXISTS SETTINGS (
	KEY	INTEGER NOT NULL,
	SLNO	INTEGER,
	BAUDRATE	INTEGER,
	PORTNAME	VARCHAR ( 100 ),
	TITLE1 VARCHAR ( 100 ),
	TITLE2 VARCHAR ( 100 ),
	FOOTER VARCHAR ( 100 ),
	PRINTER	VARCHAR ( 100 ),
	EXCLUDECUSTOMERS	BOOLEAN,
	EXCLUDECHARGES BOOLEAN,
	COPIES INTEGER,
	PRINTOPTIONFORWEIGHT	VARCHAR ( 100 ),
	EXCLUDEDRIVER	BOOLEAN,
	EXCLUDEREMARKS BOOLEAN,
	AUTOCHARGES	BOOLEAN,
	AUTOCHARGES1	BOOLEAN,
	MATERIALSL BOOLEAN,
	SMS	BOOLEAN,
	CAMERA BOOLEAN,
	SMSBAUDRATE	INTEGER,
	SMSPORTNAME	VARCHAR ( 100 ),
	LINE1	VARCHAR ( 100 ),
	LINE2	VARCHAR ( 100 ),
	LINE3	VARCHAR ( 100 ),
	LINE4	VARCHAR ( 100 ),
	NAMEOFCONTRACTOR	VARCHAR ( 100 ),
	DEPARTMENTNAME VARCHAR ( 100 ),
	SITEAT VARCHAR ( 100 ),
	TARENOSLNO BOOLEAN,
	EXCLUDEBAGS	BOOLEAN,
	BAGWEIGHT	DOUBLE,
	PRIMARY KEY ( KEY )
);

DROP TABLE IF EXISTS MATERIALS;
CREATE TABLE IF NOT EXISTS MATERIALS (
	KEY	INTEGER NOT NULL,
	MATERIALS	VARCHAR ( 100 ),
	COST	FLOAT,
	PRIMARY KEY ( KEY )
);
DROP TABLE IF EXISTS CUSTOMER;
CREATE TABLE IF NOT EXISTS CUSTOMER (
	KEY	INTEGER NOT NULL,
	CUSTOMER	VARCHAR ( 100 ),
	CUSTOMERADDRESS	VARCHAR ( 100 ),
	CUSTOMERADDRESS1	VARCHAR ( 100 ),
	PRIMARY KEY ( KEY )
);
DROP TABLE IF EXISTS CAMERA;
CREATE TABLE IF NOT EXISTS CAMERA (
	CAMERA INT NOT NULL,
	ENABLE BOOLEAN,
	NAME	VARCHAR ( 100 ),
	RESOLUTION VARCHAR ( 100 ),
	CROPX	INT,
	CROPY	INT,
	CROPWIDTH	INT,
	CROPHEIGHT INT,
	PRIMARY KEY ( CAMERA )
);
-- TABLE INSERTION;
INSERT INTO SETUP VALUES ( '2', NULL, NULL, NULL );
INSERT INTO SETTINGS VALUES( 1, 1, 1200, 'COM0;8;0;10,~~~', 'BABULENS', 'NAGERCOIL', 'FOOTER', '',
    TRUE, FALSE,  0, 'Pre Print', TRUE, TRUE, FALSE, FALSE, FALSE, FALSE, FALSE, 0,
    '', '', '', '', '', '', '', '', FALSE, TRUE, 0.0 );
INSERT INTO CAMERA VALUES ( 1, 'TRUE' , 'WEBCAM TEMP', '770 * 433', 0, 0, 770, 433 );
INSERT INTO CAMERA VALUES ( 2, 'FALSE', 'WEBCAM TEMP', ''         , 0, 0, 0  , 0   );
INSERT INTO CAMERA VALUES ( 3, 'FALSE', 'WEBCAM TEMP', ''         , 0, 0, 0  , 0   );
INSERT INTO CAMERA VALUES ( 4, 'FALSE', 'WEBCAM TEMP', ''         , 0, 0, 0  , 0   );
COMMIT;