-- TABLE UPDATES;
ALTER TABLE SETTINGS     ADD COLUMN IF NOT EXISTS  INVOICE_NO              	            INTEGER 		DEFAULT 1;
ALTER TABLE SETTINGS     ADD COLUMN IF NOT EXISTS  BAUDRATE               	            INTEGER 		DEFAULT 1200;
ALTER TABLE SETTINGS     ADD COLUMN IF NOT EXISTS  PORTNAME               	            VARCHAR(100) 	DEFAULT 'COM0;8;0;10;~~~;f';
ALTER TABLE SETTINGS     ADD COLUMN IF NOT EXISTS  TITLE1                 	            VARCHAR(100) 	DEFAULT 'BABULENS';
ALTER TABLE SETTINGS     ADD COLUMN IF NOT EXISTS  TITLE2                 	            VARCHAR(100) 	DEFAULT 'NAGERCOIL';
ALTER TABLE SETTINGS     ADD COLUMN IF NOT EXISTS  TITLE3                 	            VARCHAR(100) 	DEFAULT '';
ALTER TABLE SETTINGS     ADD COLUMN IF NOT EXISTS  FOOTER                 	            VARCHAR(100) 	DEFAULT 'FOOTER';
ALTER TABLE SETTINGS     ADD COLUMN IF NOT EXISTS  PRINTER                	            VARCHAR(100) 	DEFAULT '';
ALTER TABLE SETTINGS     ADD COLUMN IF NOT EXISTS  EXCLUDECUSTOMERS       	            BOOLEAN 		DEFAULT TRUE;
ALTER TABLE SETTINGS     ADD COLUMN IF NOT EXISTS  EXCLUDECHARGES         	            BOOLEAN 		DEFAULT FALSE;
ALTER TABLE SETTINGS     ADD COLUMN IF NOT EXISTS  COPIES                 	            INTEGER 		DEFAULT 1;
ALTER TABLE SETTINGS     ADD COLUMN IF NOT EXISTS  PRINTOPTIONFORWEIGHT   	            VARCHAR(100)	DEFAULT 'Standard';
ALTER TABLE SETTINGS     ADD COLUMN IF NOT EXISTS  REPORT                 	            VARCHAR(100)	DEFAULT 'Standard';
ALTER TABLE SETTINGS     ADD COLUMN IF NOT EXISTS  EXCLUDEDRIVER          	            BOOLEAN 		DEFAULT TRUE;
ALTER TABLE SETTINGS     ADD COLUMN IF NOT EXISTS  EXCLUDEREMARKS         	            BOOLEAN 		DEFAULT TRUE;
ALTER TABLE SETTINGS     ADD COLUMN IF NOT EXISTS  EXCLUDE_PLACE_AND_PHONE_NUMBER       BOOLEAN     	DEFAULT TRUE;
ALTER TABLE SETTINGS     ADD COLUMN IF NOT EXISTS  EXCLUDEBAGS            	            BOOLEAN 		DEFAULT TRUE;
ALTER TABLE SETTINGS     ADD COLUMN IF NOT EXISTS  EXCLUDEDCNO            	            BOOLEAN 		DEFAULT TRUE;
ALTER TABLE SETTINGS     ADD COLUMN IF NOT EXISTS  EXCLUDE_CREDIT         	            BOOLEAN 		DEFAULT TRUE;
ALTER TABLE SETTINGS     ADD COLUMN IF NOT EXISTS  EXCLUDE_VEHICLE_TYPE    	            BOOLEAN 		DEFAULT TRUE;
ALTER TABLE SETTINGS     ADD COLUMN IF NOT EXISTS  AUTOCHARGES            	            BOOLEAN 		DEFAULT FALSE;
ALTER TABLE SETTINGS     ADD COLUMN IF NOT EXISTS  MATERIALSL             	            BOOLEAN 		DEFAULT FALSE;
ALTER TABLE SETTINGS     ADD COLUMN IF NOT EXISTS  ICEWATER               	            BOOLEAN 		DEFAULT FALSE;
ALTER TABLE SETTINGS     ADD COLUMN IF NOT EXISTS  ROUND_OFF              	            BOOLEAN 		DEFAULT FALSE;
ALTER TABLE SETTINGS     ADD COLUMN IF NOT EXISTS  TARE_TOKEN             	            BOOLEAN 		DEFAULT FALSE;
ALTER TABLE SETTINGS     ADD COLUMN IF NOT EXISTS  EXIT_PASS              	            BOOLEAN  		DEFAULT FALSE;
ALTER TABLE SETTINGS     ADD COLUMN IF NOT EXISTS  SMS                    	            BOOLEAN 		DEFAULT FALSE;
ALTER TABLE SETTINGS     ADD COLUMN IF NOT EXISTS  CAMERA                 	            BOOLEAN 		DEFAULT FALSE;
ALTER TABLE SETTINGS     ADD COLUMN IF NOT EXISTS  SMSBAUDRATE            	            INTEGER 		DEFAULT 9600;
ALTER TABLE SETTINGS     ADD COLUMN IF NOT EXISTS  SMSPORTNAME            	            VARCHAR(100)	DEFAULT 'COM0';
ALTER TABLE SETTINGS     ADD COLUMN IF NOT EXISTS  LINE1                  	            VARCHAR(100)	DEFAULT '';
ALTER TABLE SETTINGS     ADD COLUMN IF NOT EXISTS  LINE2                  	            VARCHAR(100)	DEFAULT '';
ALTER TABLE SETTINGS     ADD COLUMN IF NOT EXISTS  LINE3                  	            VARCHAR(100)	DEFAULT '';
ALTER TABLE SETTINGS     ADD COLUMN IF NOT EXISTS  LINE4                  	            VARCHAR(100)	DEFAULT '';
ALTER TABLE SETTINGS     ADD COLUMN IF NOT EXISTS  NAME_OF_WORK           	            VARCHAR(200)	DEFAULT '';
ALTER TABLE SETTINGS     ADD COLUMN IF NOT EXISTS  NAME_OF_CONTRACTOR     	            VARCHAR(100)	DEFAULT '';
ALTER TABLE SETTINGS     ADD COLUMN IF NOT EXISTS  DEPARTMENT_NAME        	            VARCHAR(100)	DEFAULT '';
ALTER TABLE SETTINGS     ADD COLUMN IF NOT EXISTS  SITE_AT                	            VARCHAR(100)	DEFAULT '';
ALTER TABLE SETTINGS     ADD COLUMN IF NOT EXISTS  AGREEMENT_NO           	            VARCHAR(100)	DEFAULT '';
ALTER TABLE SETTINGS     ADD COLUMN IF NOT EXISTS  ESTIMATE_NO            	            VARCHAR(100)	DEFAULT '';
ALTER TABLE SETTINGS     ADD COLUMN IF NOT EXISTS  OPERATOR              	            VARCHAR(100)	DEFAULT '';
ALTER TABLE SETTINGS     ADD COLUMN IF NOT EXISTS  INVOICE_PROPERTY        	            VARCHAR(100)	DEFAULT '';
ALTER TABLE SETTINGS     ADD COLUMN IF NOT EXISTS  TARENOSLNO             	            BOOLEAN 		DEFAULT FALSE;
ALTER TABLE SETTINGS     ADD COLUMN IF NOT EXISTS  BAGWEIGHT              	            DOUBLE 		    DEFAULT 0.0;
ALTER TABLE SETTINGS     ADD COLUMN IF NOT EXISTS  ROUND_OFF_DECIMALS     	            INTEGER 		DEFAULT 0;
ALTER TABLE SETTINGS     ADD COLUMN IF NOT EXISTS  NEED_LOGIN             	            BOOLEAN 		DEFAULT FALSE;
ALTER TABLE SETTINGS     ADD COLUMN IF NOT EXISTS  NEED_PRINT_COPY_DIALOG 	            BOOLEAN 		DEFAULT FALSE;
ALTER TABLE SETTINGS     ADD COLUMN IF NOT EXISTS  SHOW_STATUS            	            BOOLEAN 		DEFAULT FALSE;
ALTER TABLE SETTINGS     ADD COLUMN IF NOT EXISTS  TAKE_BACKUP            	            BOOLEAN 		DEFAULT TRUE;
ALTER TABLE SETTINGS     ADD COLUMN IF NOT EXISTS  SHOW_INVOICE            	            BOOLEAN 		DEFAULT FALSE;
ALTER TABLE SETTINGS     ADD COLUMN IF NOT EXISTS  KOTTA_SETTING           	            BOOLEAN 		DEFAULT FALSE;
ALTER TABLE SETTINGS     ADD COLUMN IF NOT EXISTS  TRIAL_LICENSE_PASSWORD 	            VARCHAR(20) 	DEFAULT '147085';
ALTER TABLE SETTINGS     ADD COLUMN IF NOT EXISTS  LICENSE_PASSWORD       	            VARCHAR(20) 	DEFAULT '147085aA';
ALTER TABLE SETTINGS     ADD COLUMN IF NOT EXISTS  UNLOCK_PASSWORD        	            VARCHAR(20) 	DEFAULT '147085';
ALTER TABLE SETTINGS     ADD COLUMN IF NOT EXISTS  CAMERA_PASSWORD        	            VARCHAR(20) 	DEFAULT '147085';
ALTER TABLE SETTINGS     ADD COLUMN IF NOT EXISTS  SMS_PASSWORD           	            VARCHAR(20) 	DEFAULT '147085';
ALTER TABLE SETTINGS     ADD COLUMN IF NOT EXISTS  INVOICE_PASSWORD        	            VARCHAR(20) 	DEFAULT '147085';
ALTER TABLE SETTINGS     ADD COLUMN IF NOT EXISTS  MANUAL_ENTRY_PASSWORD  	            VARCHAR(20) 	DEFAULT '147085';
ALTER TABLE SETTINGS     ADD COLUMN IF NOT EXISTS  EDIT_ENABLE_PASSWORD   	            VARCHAR(20) 	DEFAULT '147085';
ALTER TABLE SETTINGS     ADD COLUMN IF NOT EXISTS  RESET_PASSWORD         	            VARCHAR(20) 	DEFAULT '147085';
ALTER TABLE SETTINGS     ADD COLUMN IF NOT EXISTS  LOGIN_PASSWORD                       VARCHAR(20) 	DEFAULT '123';

ALTER TABLE VEHICLETARES ALTER COLUMN IF EXISTS "KEY" RENAME TO SQNO;
DELETE FROM VEHICLETARES WHERE SQNO IS NULL;
ALTER TABLE VEHICLETARES ALTER COLUMN SQNO SET NOT NULL;
ALTER TABLE VEHICLETARES DROP PRIMARY KEY;
ALTER TABLE VEHICLETARES ADD PRIMARY KEY (SQNO);
ALTER TABLE VEHICLETARES ADD COLUMN IF NOT EXISTS  CUSTOMERNAME                         VARCHAR(100)    DEFAULT '';
ALTER TABLE VEHICLETARES ADD COLUMN IF NOT EXISTS  VEHICLENO                            VARCHAR(100)    DEFAULT '';
ALTER TABLE VEHICLETARES ADD COLUMN IF NOT EXISTS  PLACE                                VARCHAR(100)    DEFAULT '';
ALTER TABLE VEHICLETARES ADD COLUMN IF NOT EXISTS  PHONE_NUMBER                         VARCHAR(100)    DEFAULT '';
ALTER TABLE VEHICLETARES ADD COLUMN IF NOT EXISTS  TAREWT                               INTEGER         DEFAULT 0;
ALTER TABLE VEHICLETARES ADD COLUMN IF NOT EXISTS  TAREDATE                             DATE            DEFAULT NOW();
ALTER TABLE VEHICLETARES ADD COLUMN IF NOT EXISTS  TARETIME                             TIME            DEFAULT NOW();

ALTER TABLE WEIGHING     ADD COLUMN IF NOT EXISTS  PLACE                                VARCHAR(100)    DEFAULT '';
ALTER TABLE WEIGHING     ADD COLUMN IF NOT EXISTS  PHONE_NUMBER                         VARCHAR(100)    DEFAULT '';
ALTER TABLE WEIGHING     ADD COLUMN IF NOT EXISTS  VEHICLE_TYPE                         VARCHAR(100)    DEFAULT '';
ALTER TABLE WEIGHING     ADD COLUMN IF NOT EXISTS  OPERATOR                             VARCHAR(100)    DEFAULT '';
ALTER TABLE WEIGHING     ADD COLUMN IF NOT EXISTS  CREDIT                               BOOLEAN         DEFAULT FALSE;
ALTER TABLE WEIGHING     ADD COLUMN IF NOT EXISTS  DEDUCTION_OR_PER_COST                DOUBLE          DEFAULT 0;
ALTER TABLE WEIGHING     ADD COLUMN IF NOT EXISTS  ROUND_OFF                            DOUBLE          DEFAULT 0;

DELETE FROM CUSTOMER WHERE CUSTOMER IS NULL;
ALTER TABLE CUSTOMER ALTER COLUMN CUSTOMER SET NOT NULL;
ALTER TABLE CUSTOMER DROP COLUMN IF EXISTS SQNO;
ALTER TABLE CUSTOMER DROP COLUMN IF EXISTS CUSTOMERADDRESS;
ALTER TABLE CUSTOMER DROP COLUMN IF EXISTS CUSTOMERADDRESS1;
ALTER TABLE CUSTOMER DROP COLUMN IF EXISTS "KEY";
ALTER TABLE CUSTOMER DROP PRIMARY KEY;
ALTER TABLE CUSTOMER ADD PRIMARY KEY (CUSTOMER);

CREATE TABLE IF NOT EXISTS INVOICES
(
    INVOICE_NO               INTEGER NOT NULL,
    INVOICE_DATA             VARCHAR(2000),
    PRIMARY KEY (INVOICE_NO)
);

CREATE TABLE IF NOT EXISTS VEHICLE_TYPES
(
    VEHICLE_TYPE                VARCHAR(100) NOT NULL,
    TARE_COST                   INTEGER,
    GROSS_COST                  INTEGER,
    PRIMARY KEY (VEHICLE_TYPE)
);
ALTER TABLE VEHICLE_TYPES ADD COLUMN IF NOT EXISTS  TARE_COST       INTEGER DEFAULT 0;
ALTER TABLE VEHICLE_TYPES ADD COLUMN IF NOT EXISTS  GROSS_COST      INTEGER DEFAULT 0;

CREATE TABLE IF NOT EXISTS OPERATORS
(
    OPERATOR                     VARCHAR(100) NOT NULL,
    PRIMARY KEY (OPERATOR)
);

CREATE TABLE IF NOT EXISTS TRANSPORTER
(
    TRANSPORTER              VARCHAR(100) NOT NULL,
    PRIMARY KEY (TRANSPORTER)
);

ALTER TABLE OPERATORS ALTER COLUMN IF EXISTS OPERATORS RENAME TO OPERATOR;
ALTER TABLE VEHICLE_TYPES ALTER COLUMN IF EXISTS VEHICLE_TYPES RENAME TO VEHICLE_TYPE;

ALTER TABLE MATERIALS ALTER COLUMN IF EXISTS "KEY" RENAME TO SQNO;