name: WeighBridge 1.0

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: windows-latest

    strategy:
      matrix:
        java-version: ['8', '17']

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4
      
      # Set up JDK
      - name: Set up JDK ${{ matrix.java-version }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java-version }}
          distribution: 'adopt'
      
      # Build the project using Maven
      - name: Build with Maven
        run: mvn clean package verify
      
      # Upload the build artifacts
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: WeighBridge 1.0 jdk${{ matrix.java-version }}
          path: WeighBridge 1.0
