name: WeighBridge 1.0
on:
  push:
    branches: [ "master" ]
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'adopt'
      - run: mvn clean package verify
      - uses: actions/upload-artifact@v3.1.2
        with:
          name: WeighBridge 1.0
          path: WeighBridge 1.0
