name: WeighBridge 1.0

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3
      
      # Set up JDK 8
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'adopt'
      
      # Build the project using Maven
      - name: Build with Maven
        run: mvn clean package verify
      
      # Upload the build artifacts
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: WeighBridge-1.0
          path: WeighBridge 1.0
